##Add additional Host cluster Node IPs as BGP neighbors
apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: bgp-host-cl
  namespace: frr-k8s
spec:
  bgp:
    routers:
      - asn: 64512
        neighbors:
          - address: 192.168.8.99
            asn: 64511
            ebgpMultiHop: true
            toAdvertise:
              allowed:
                mode: all
        prefixes:
          - 10.10.12.16/28
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.10.12.16/28
